### ISSUE TITLE
Tilda tabs are is transparent in Ubuntu 16.04

### ISSUE THREAD

**Issue by Defcon0** [lanoxx/tilda#257]
Hello,

in Ubuntu 16.04, the tab bar is transparent and I cannot remove that. Is it a bug?

![tilda](https://cloud.githubusercontent.com/assets/1485098/18419712/395b0888-7861-11e6-892d-f6a0a82373fc.png)

Bye Defcon0

**Comment by joshbenner** [comment]
IMO, it's a bug. I've worked around it by setting a stylesheet as demonstrated in the wiki.

**Comment by moisadoru** [comment]
In Ubuntu 16.10 (tilda 1.3.1), the stylesheet workaround no longer works.

**Comment by moisadoru** [comment]
I managed to make the custom stylesheet work by using other css selectors than the ones in the wiki:
```css
notebook > header {
  background-color: rgba(51,51,51,.9);
  border: none;
}

notebook > header > tabs > tab {
  background-color: rgba(80,80,80,.9);
  border-radius: 0;
  color: #ccc;
  border: 0;
  margin: 0 1px;
  border-width: 0 1px;
  min-width: 100px;
  box-shadow: none;
}
notebook > header > tabs > tab > label {
  text-align: left;
}
notebook > header > tabs > tab:checked {
  background: rgba(0,0,0,.8);
  color: orange;
}
```
