### ISSUE TITLE
How to hide the blue bar in active tab

### ISSUE THREAD

**Issue by omaressameldin** [lanoxx/tilda#447]
I am trying to hide the blue border for active tab as you can see here
![image](https://user-images.githubusercontent.com/10829786/100458547-e261a600-30bb-11eb-9945-b3206295ed38.png)
 but I am unable to do so. This is my style.css
```css
/* 1 */
notebook > header {
    background-color: rgba(30,31,41,1);
    border: none;
    margin: 0;
    padding:0;
  }

  /* 2 */
  notebook > header > tabs {
    background: rgba(30,31,41,1);
    background-color: rgba(30,31,41,1);
    border: none;
    box-shadow:  0px 5px 10px rgba(0,0,0,0.2);
  }

  /* 3 */
  notebook > header > tabs > tab {
    background: rgba(30,31,41,1);
    color: #4c5e63;
    border: none;
    padding: 6px;
    min-width: 100px;
    border-radius: 0px;
  }

  /* 4 */
  notebook > header > tabs > tab:checked {
    color: #FCBFB7;
    border-bottom: 5px solid rgba(51, 153, 137,0.8);
    border-image: none;
  }
```
